language: node_js
node_js:
  - '6'
addons:
  firefox: latest
sudo: false
install:
  - yarn
script:
  - export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    set -e;
    pushd packages/widgets;
    yarn build;
    popd;
    yarn clean;
    yarn build;
    yarn test;
