language: node_js
node_js:
  - '0.12'
sudo: false
env:
  matrix:
    - GROUP=
    - GROUP=docs
  global:
    - secure: Zv6POtOhi0kIMgvGnt3dGouLc+hXeajKuoBMUPLdYdkeD/JLhNHyZyZkF7SKKeKcVSCUj8Y20hcWH2rErRckvGO3jUdeupUZN5DnwKnFZ2QXF4/s7+xzSR5jbS5IUbL9YVPoxSXMyK7VtkcGa1M4H/1cZYOdSUIz51pkfXipgus=
install:
  - npm install -g tsd@next
  - npm install -g typedoc
  - npm install -g gulp
  - npm install
  - 'echo "{\"token\": \"$GHTOKEN\"}" > ~/.tsdrc'
  - tsd rate
  - tsd reinstall -so
  - gulp
script:
  - if [[ $GROUP == docs ]]; then gulp examples; gulp docs; fi
  - true
after_success: |
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'master' ]]
  then
    echo "Will build Documentation"
    gulp examples
    echo 'Phosphor examples' > index.html
    git config credential.helper 'store --file=.git/credentials'
    git remote add ghpages https://github.com/phosphorjs/phosphor.git
    echo "https://${GHTOKEN}:@github.com" > .git/credentials
    git config --global user.email "travis@travis-ci.com"
    git config --global user.name "Travis Bot"
    git add index.html
    git add -f dist
    git add -f examples
    git add -f docs
    git commit -am'autocommit docs'
    git checkout -b gh-pages
    git push ghpages gh-pages:gh-pages -f
  else
    echo "Will only deploy docs build from phosphor master branch"
  fi

